[DirectDraw Test Application]
BufferSize.Window=51200
LogFile.Log File=c:\ddtests\fnddraw.log
Cmd.Size=1
Cmd.Hex0000=00
ModesToTest=4
DirectDrawInterface=2
DirectDrawSurfaceInterface=1
DirectDrawInitStyle=2
TreatOtherAsPass=0
MonitorIndex=0
LogBMP=0
StopOnFail=0
Position=195, 135, 1475, 902
Options=387
RunCount=1
Search=failure
LogWindowLevel=10
LogLog FileLevel=10
FontName=Courier
FontAttr=-2 400 0 131585
NumTests=51
testcasename0050=API Test cases\API_ClassFactory
testcasename0049=API Test cases\API_IV_GetMonitorFrequency
testcasename0048=API Test cases\API_IV_EnumDisplayModes
testcasename0047=API Test cases\API_IV_QueryInterface
testcasename0046=API Test cases\API_IV_CreatePalette
testcasename0045=API Test cases\API_IV_GetScanLine
testcasename0044=API Test cases\API_IV_Initialize
testcasename0043=API Test cases\API_IV_AddRef
testcasename0042=API Test cases\API_IV_FlipToGDISurface
testcasename0041=API Test cases\API_IV_RestoreDisplayMode
testcasename0040=API Test cases\API_IV_Compact
testcasename0039=API Test cases\API_IV_Release
testcasename0038=API Test cases\API_IV_SetDisplayMode
testcasename0037=API Test cases\API_IV_EnumSurfaces
testcasename0036=API Test cases\API_IV_WaitForVerticalBlank
testcasename0035=API Test cases\API_IV_GetVerticalBlankStatus
testcasename0034=API Test cases\API_IV_SetCooperativeLevel
testcasename0033=API Test cases\API_IV_Unlock
testcasename0032=API Test cases\API_IV_GetCaps
testcasename0031=API Test cases\API_IV_GetDisplayMode
testcasename0030=API Test cases\API_IV_GetFourCCCodes
testcasename0029=API Test cases\API_IV_Flip
testcasename0028=API Test cases\API_IV_GetAvailableVidMem
testcasename0027=API Test cases\API_IV_SurfQueryInterface
testcasename0026=API Test cases\API_IV_GetGDISurface
testcasename0025=API Test cases\API_TestCooperativeLevel
testcasename0024=API Test cases\API_GetDeviceIdentifier
testcasename0023=API Test cases\API_Lander
testcasename0022=API Test cases\API_SetDisplayMode
testcasename0021=API Test cases\API_GetMonitorFrequency
testcasename0020=API Test cases\API_GetScanLine
testcasename0019=API Test cases\API_GetVerticalBlankStatus
testcasename0018=API Test cases\API_Initialize
testcasename0017=API Test cases\API_RestoreDisplayMode
testcasename0016=API Test cases\API_Lock
testcasename0015=API Test cases\API_FlipToGDISurface
testcasename0014=API Test cases\API_GetGDISurface
testcasename0013=API Test cases\API_GetDisplayMode
testcasename0012=API Test cases\API_GetCaps
testcasename0011=API Test cases\API_EnumSurfaces
testcasename0010=API Test cases\API_GetFourCCCodes
testcasename0009=API Test cases\API_EnumDisplayModes
testcasename0008=API Test cases\API_DuplicateSurf
testcasename0007=API Test cases\API_HEL_CreateSurface
testcasename0006=API Test cases\API_CreateSurf
testcasename0005=API Test cases\API_IV_CreateSurf
testcasename0004=API Test cases\API_Compact
testcasename0003=API Test cases\API_QueryInterface
testcasename0002=API Test cases\API_AddRef/Release
testcasename0001=API Test cases\API_DirectDrawEnumerate
testcasename0000=API Test cases\API_IV_DirectDrawCreate
