[DirectDraw Test Application]
BufferSize.Window=51200
LogFile.Log File=c:\ddtests\fnddraw.log
Cmd.Size=1
Cmd.Hex0000=00
ModesToTest=4
DirectDrawInterface=2
DirectDrawSurfaceInterface=1
DirectDrawInitStyle=2
TreatOtherAsPass=0
MonitorIndex=0
LogBMP=0
StopOnFail=0
Position=0, 0, 1024, 690
Options=387
RunCount=1
Search=failure
LogWindowLevel=10
LogLog FileLevel=10
FontName=Courier
FontAttr=-2 400 0 131585
NumTests=88
testcasename0087=BLT Test cases\BLT_BltFast Vid to AGP
testcasename0086=BLT Test cases\BLT_BltFast Vid to Sys
testcasename0085=BLT Test cases\BLT_BltFast Vid to Vid
testcasename0084=BLT Test cases\BLT_BltFast AGP to Vid
testcasename0083=BLT Test cases\BLT_BltFast AGP to Sys (Driver may return DDERR_UNSUPPORTED)
testcasename0082=BLT Test cases\BLT_BltFast AGP to AGP
testcasename0081=BLT Test cases\BLT_BltFast Sys to AGP
testcasename0080=BLT Test cases\BLT_BltFast Sys to Vid
testcasename0079=BLT Test cases\BLT_BltFast Sys to Sys
testcasename0078=BLT Test cases\BLT_InvalidFlagsDDFX
testcasename0077=BLT Test cases\BLT_CanNotDepthFill
testcasename0076=BLT Test cases\BLT_CanNotColorFill
testcasename0075=BLT Test cases\BLT_NoDestColorKey
testcasename0074=BLT Test cases\BLT_NoSrcColorKey
testcasename0073=BLT Test cases\BLT_Texture Vid to Vid
testcasename0072=BLT Test cases\BLT_Texture Sys to AGP
testcasename0071=BLT Test cases\BLT_Texture Sys to Vid
testcasename0070=BLT Test cases\BLT_Texture Sys to Sys
testcasename0069=BLT Test cases\BLT_ColorConverting
testcasename0068=BLT Test cases\BLT_SafeLockPri
testcasename0067=BLT Test cases\BLT_OffscreenOverlap
testcasename0066=BLT Test cases\BLT_OnscreenOverlap
testcasename0065=BLT Test cases\BLT_BltFrontToBackBuff
testcasename0064=BLT Test cases\BLT_GetBltStatusPostFlip
testcasename0063=BLT Test cases\BLT_GetBltStatusMultBlts
testcasename0062=BLT Test cases\BLT,Invalid Params Test(TC 3.6.1-3, 3.6.5, 3.6.7-8 )
testcasename0061=BLT Test cases\BLT, Blt with CS_PARENTDC clip window(#5673)
testcasename0060=BLT Test cases\BLT_ZBuffer
testcasename0059=BLT Test cases\BLT, DDERR_NOROTATIONHW (Manbug4.1#8172)
testcasename0058=BLT Test cases\BLT, SRCKEY (from VMem) with unused pixel bits set
testcasename0057=BLT Test cases\BLT, SRCKEY with unused pixel bits set (#5663)
testcasename0056=BLT Test cases\BLT_BltFast - Verify RLE recompression triggered
testcasename0055=BLT Test cases\BLT_BltFast - MoveToSytemMemoryTest
testcasename0054=BLT Test cases\BLT, FourCC to FourCC(TC# ?]
testcasename0053=BLT Test cases\BLT, FourCC to RGB stretch (TC#??.??.]
testcasename0052=BLT Test cases\BLT, FourCC to RGB conversion (TC#??.??.]
testcasename0051=BLT Test cases\BLT_BltFast, SRCKEY, From/To same surface (TC#3.6.97b)
testcasename0050=BLT Test cases\BLT_BltFast From/To Same Surface(TC#3.6.97a)
testcasename0049=BLT Test cases\BLT, Stretch (Wx2, Hx.75), AGP to Pri
testcasename0048=BLT Test cases\BLT, Stretch (Wx2, Hx.75), Sys to Pri
testcasename0047=BLT Test cases\BLT, Stretch (Wx2, Hx.75), VMem to Pri
testcasename0046=BLT Test cases\BLT, Shrink, (3/4), AGP To Primary
testcasename0045=BLT Test cases\BLT, Shrink, (3/4), Sys To Primary
testcasename0044=BLT Test cases\BLT, Shrink, (3/4), VMem To Primary
testcasename0043=BLT Test cases\BLT, Mirrored and Clipped (Manbug4.1#13532)
testcasename0042=BLT Test cases\BLT, Border clipping test
testcasename0041=BLT Test cases\BLT, Clipped, System to Primary Test
testcasename0040=BLT Test cases\BLT, Clipped, VMem to Primary Test
testcasename0039=BLT Test cases\BLT Color Fill AGP Mem(TC 3.6.57)
testcasename0038=BLT Test cases\BLT Color Fill SysMem(TC 3.6.57)
testcasename0037=BLT Test cases\BLT Color Fill Primary(TC 3.6.57)
testcasename0036=BLT Test cases\BLT,ROPs, System to Primary(TC 3.6.84)
testcasename0035=BLT Test cases\BLT,ROPs, VMem to Primary (TC 3.6.84)
testcasename0034=BLT Test cases\BLT, Stretch, Complete Overlap, AGP mem.(TC 3.6.?]
testcasename0033=BLT Test cases\BLT, Stretch, Complete Overlap, Sys. mem.(TC 3.6.?]
testcasename0032=BLT Test cases\BLT, Stretch, Complete Overlap, VMem(primary)(TC 3.6.?]
testcasename0031=BLT Test cases\BLT,Stretch(width only), SRCKEY, AGP to pri(TC 3.6.?]
testcasename0030=BLT Test cases\BLT,Stretch(width only), SRCKEY, VMem to pri(TC 3.6.?]
testcasename0029=BLT Test cases\BLT,Stretch(width only), SRCKEY, Sys to pri(TC 3.6.?]
testcasename0028=BLT Test cases\BLT,Stretch, SRCKEY, AGP to primary(TC 3.6.?]
testcasename0027=BLT Test cases\BLT,Stretch, SRCKEY, VMem to primary(TC 3.6.?]
testcasename0026=BLT Test cases\BLT,Stretch, SRCKEY, System to primary(TC 3.6.?]
testcasename0025=BLT Test cases\BLT, DESTKEY Space, VMem to Primary(TC 3.6.?]
testcasename0024=BLT Test cases\BLT, DESTKEY Space, System to Primary(TC 3.6.?]
testcasename0023=BLT Test cases\BLT, single DESTKEY, AGP to Primary(TC 3.6.60)
testcasename0022=BLT Test cases\BLT, single DESTKEY, VMem to Primary(TC 3.6.58)
testcasename0021=BLT Test cases\BLT, single DESTKEY, System to Primary(TC 3.6.58)
testcasename0020=BLT Test cases\BLT, SRCKEY Space, VMem to Primary(TC 3.6.?]
testcasename0019=BLT Test cases\BLT, SRCKEY Space, System to Primary(TC 3.6.?]
testcasename0018=BLT Test cases\BLT, single SRCKEY, AGP to Primary(TC 3.6.60)
testcasename0017=BLT Test cases\BLT, single SRCKEY, VMem to Primary(TC 3.6.60)
testcasename0016=BLT Test cases\BLT, single SRCKEY, System to Primary(TC 3.6.60)
testcasename0015=BLT Test cases\BLT Stretch(width only) x 1.5, AGP to Pri(TC 3.6.51-52)
testcasename0014=BLT Test cases\BLT Stretch(width only) x 1.5, System to Pri(TC 3.6.51-52)
testcasename0013=BLT Test cases\BLT Stretch(width only) x 1.5, VMem to Pri(TC 3.6.51-52)
testcasename0012=BLT Test cases\BLT Shrink (1/2), AGP to Primary(TC 3.6.53-54)
testcasename0011=BLT Test cases\BLT Shrink (1/2), System to Primary(TC 3.6.53-54)
testcasename0010=BLT Test cases\BLT Shrink (1/2), VMem to Primary(TC 3.6.53-54)
testcasename0009=BLT Test cases\BLT Stretch x 1.5, AGP to Primary(TC 3.6.51-52)
testcasename0008=BLT Test cases\BLT Stretch x 1.5, System to Primary(TC 3.6.51-52)
testcasename0007=BLT Test cases\BLT Stretch x 1.5, VMem to Primary(TC 3.6.51-52)
testcasename0006=BLT Test cases\BLT Stretch x 2, AGP to Primary(TC 3.6.49-50)
testcasename0005=BLT Test cases\BLT Stretch x 2, System to Primary(TC 3.6.49-50)
testcasename0004=BLT Test cases\BLT Stretch x 2, VMem to Primary(TC 3.6.49-50)
testcasename0003=BLT Test cases\BLT Basic, AGP to Primary(TC 3.6.48, 3.6.103)
testcasename0002=BLT Test cases\BLT Basic, System to Primary(TC 3.6.48, 3.6.107)
testcasename0001=BLT Test cases\BLT Basic, VMem to Primary(TC 3.6.48, 3.6.103)
testcasename0000=BLT Test cases\BLT Basic, Offscreen Surfaces(TC 3.6.101-102, 2.6.105-106)
