[DirectDraw Test Application]
BufferSize.Window=51200
LogFile.Log File=c:\ddtests\fnddraw.log
Cmd.Size=1
Cmd.Hex0000=00
ModesToTest=4
DisplayModeWidth=1680
DisplayModeHeight=1050
DisplayModeBPP=32
DisplayModeRefreshRate=60
DirectDrawInterface=2
DirectDrawSurfaceInterface=1
DirectDrawInitStyle=2
TreatOtherAsPass=0
MonitorIndex=0
LogBMP=0
StopOnFail=0
Position=4294967295, 0, 1679, 1050
Options=387
RunCount=1
Search=failure
LogWindowLevel=10
LogLog FileLevel=10
FontName=Courier
FontAttr=-2 400 0 131585
NumTests=72
testcasename0054=API Test cases\API_ClassFactory
testcasename0053=API Test cases\API_IV_GetMonitorFrequency
testcasename0052=API Test cases\API_IV_EnumDisplayModes
testcasename0051=API Test cases\API_IV_QueryInterface
testcasename0050=API Test cases\API_IV_GetScanLine
testcasename0049=API Test cases\API_IV_Initialize
testcasename0048=API Test cases\API_IV_AddRef
testcasename0047=API Test cases\API_IV_FlipToGDISurface
testcasename0046=API Test cases\API_IV_RestoreDisplayMode
testcasename0045=API Test cases\API_IV_Compact
testcasename0044=API Test cases\API_IV_Release
testcasename0043=API Test cases\API_IV_EnumSurfaces
testcasename0042=API Test cases\API_IV_WaitForVerticalBlank
testcasename0041=API Test cases\API_IV_GetVerticalBlankStatus
testcasename0040=API Test cases\API_IV_SetCooperativeLevel
testcasename0039=API Test cases\API_IV_Unlock
testcasename0038=API Test cases\API_IV_GetCaps
testcasename0037=API Test cases\API_IV_GetDisplayMode
testcasename0036=API Test cases\API_IV_GetFourCCCodes
testcasename0035=API Test cases\API_IV_GetAvailableVidMem
testcasename0034=API Test cases\API_IV_SurfQueryInterface
testcasename0033=API Test cases\API_IV_GetGDISurface
testcasename0032=API Test cases\API_TestCooperativeLevel
testcasename0031=API Test cases\API_GetDeviceIdentifier
testcasename0030=API Test cases\API_Lander
testcasename0029=API Test cases\API_SetDisplayMode
testcasename0028=API Test cases\API_GetMonitorFrequency
testcasename0027=API Test cases\API_GetScanLine
testcasename0026=API Test cases\API_Initialize
testcasename0025=API Test cases\API_RestoreDisplayMode
testcasename0024=API Test cases\API_Lock
testcasename0023=API Test cases\API_FlipToGDISurface
testcasename0022=API Test cases\API_GetDisplayMode
testcasename0021=API Test cases\API_GetCaps
testcasename0020=API Test cases\API_EnumSurfaces
testcasename0019=API Test cases\API_EnumDisplayModes
testcasename0018=API Test cases\API_DuplicateSurf
testcasename0017=API Test cases\API_HEL_CreateSurface
testcasename0016=API Test cases\API_CreateSurf
testcasename0015=API Test cases\API_IV_CreateSurf
testcasename0014=API Test cases\API_Compact
testcasename0013=API Test cases\API_QueryInterface
testcasename0012=API Test cases\API_AddRef/Release
testcasename0011=API Test cases\API_DirectDrawEnumerate
testcasename0010=API Test cases\API_IV_DirectDrawCreate
testcasename0009=DCT Test cases\DCT_AGPPrimarySurface
testcasename0008=DCT Test cases\DCT_ColorFillWithSourceSurface
testcasename0007=DCT Test cases\DCT_LargeNumberOfBuffersPageFlipping
testcasename0006=DCT Test cases\GRPH-0393.1 Mobile Minimum Screen Resolution
testcasename0005=DCT Test cases\PC99 14.22 App Access. FrameBuff1
testcasename0004=DCT Test cases\PC99 14.23 Low-Res Support
testcasename0003=DCT Test cases\PC98_23 (PC97 22) Programmable Blter Stride
testcasename0002=DCT Test cases\PC98_22 (PC97 20) Perform Double Buffer Swaps with no tearing
testcasename0001=DCT Test cases\PC98_21 (PC97 19) Transparent Blter
testcasename0000=DCT Test cases\DCT_GetCaps ROP verification (DCT 5.20.1)
testcasename0071=CLIP Test cases\CLIP_QueryInterface
testcasename0070=CLIP Test cases\CLIP_Initialize
testcasename0069=CLIP Test cases\CLIP_QueryInterface Invalid Params Test
testcasename0068=CLIP Test cases\CLIP_IsClipListChanged - Invalid Params Test(TC 5.7.1-2)
testcasename0067=CLIP Test cases\CLIP_GetClipList - Invalid Params Test(TC 5.4.1-6)
testcasename0066=CLIP Test cases\CLIP_SetClipList While Using HWnd Test(TC 5.8.11)
testcasename0065=CLIP Test cases\CLIP_SetClipList/GetClipList Test(TC 5.4.8, 5.8.9-10)
testcasename0064=CLIP Test cases\CLIP_SetHWnd/GetHWnd Test(TC 5.5.4, 5.9.5)
testcasename0063=PAL Test cases\PAL_MultiPalSwitch
testcasename0062=PAL Test cases\PAL_palGetPalette Test's surface get palette
testcasename0061=PAL Test cases\PAL_Set New Palette Test (Regress: #8154)
testcasename0060=PAL Test cases\PAL_Palette AddRef/Release Test (TC 4.2.2-3, 4.3.2-3 )
testcasename0059=PAL Test cases\PAL_Palette Initialize Test(TC 4.6.3)
testcasename0058=PAL Test cases\PAL_Verify Palette Entries Untouched(Regress Nash #7535)
testcasename0057=PAL Test cases\PAL_GetEntries/SetEntries (8-Bit)(TC 4.5.7, 4.7.7)
testcasename0056=PAL Test cases\PAL_CreatePalette - ALLOW256 Test(TC 2.6.12)
testcasename0055=PAL Test cases\PAL_CreatePalette - Init 256 clrs(TC 2.6.9)
