[DirectDraw Test Application]
BufferSize.Window=51200
LogFile.Log File=c:\ddtests\fnddraw.log
Cmd.Size=1
Cmd.Hex0000=00
ModesToTest=4
DirectDrawInterface=2
DirectDrawSurfaceInterface=1
DirectDrawInitStyle=2
TreatOtherAsPass=0
MonitorIndex=0
LogBMP=0
StopOnFail=0
Position=0, 105, 1277, 872
Options=387
RunCount=1
Search=failure
LogWindowLevel=10
LogLog FileLevel=10
FontName=Courier
FontAttr=-2 400 0 131585
NumTests=121
testcasename0120=SURF Test cases\SURF_IV_EnumAttachedSurfaces
testcasename0119=SURF Test cases\SURF_IV_AddAttachedSurface
testcasename0118=SURF Test cases\SURF_IV_DuplicateSurface
testcasename0117=SURF Test cases\SURF_IV_GetAttachedSurface
testcasename0116=SURF Test cases\SURF_IV_GetCaps
testcasename0115=SURF Test cases\SURF_IV_GetClipper
testcasename0114=SURF Test cases\SURF_IV_SetClipper
testcasename0113=SURF Test cases\SURF_IV_GetDDInterface
testcasename0112=SURF Test cases\SURF_IV_Initialize
testcasename0111=SURF Test cases\SURF_IV_Blt
testcasename0110=SURF Test cases\SURF_IV_BltFast
testcasename0109=SURF Test cases\SURF_IV_BltBatch
testcasename0108=SURF Test cases\SURF_IV_GetColorKey
testcasename0107=SURF Test cases\SURF_IV_ReleaseDC
testcasename0106=SURF Test cases\SURF_IV_GetBltStatus
testcasename0105=SURF Test cases\CSEM_Blt Custom Memory Surfaces
testcasename0104=SURF Test cases\SURF_GetSurfaceDesc
testcasename0103=SURF Test cases\SURF_WideSurfaces
testcasename0102=SURF Test cases\SURF_QueryInterface, multiple buffer surface
testcasename0101=DC Test cases\API_GetDC, Verify Pixel Format(TC ?]
testcasename0100=DC Test cases\Get/Release DC x 25(TC ?]
testcasename0099=BLT Test cases\BLT_BltFast Vid to AGP
testcasename0098=BLT Test cases\BLT_BltFast Vid to Sys
testcasename0097=BLT Test cases\BLT_BltFast Vid to Vid
testcasename0096=BLT Test cases\BLT_BltFast AGP to Vid
testcasename0095=BLT Test cases\BLT_BltFast AGP to Sys (Driver may return DDERR_UNSUPPORTED)
testcasename0094=BLT Test cases\BLT_BltFast AGP to AGP
testcasename0093=BLT Test cases\BLT_BltFast Sys to AGP
testcasename0092=BLT Test cases\BLT_BltFast Sys to Vid
testcasename0091=BLT Test cases\BLT_BltFast Sys to Sys
testcasename0090=BLT Test cases\BLT_OnscreenOverlap
testcasename0089=BLT Test cases\BLT_BltFrontToBackBuff
testcasename0088=BLT Test cases\BLT, SRCKEY (from VMem) with unused pixel bits set
testcasename0087=BLT Test cases\BLT, SRCKEY with unused pixel bits set (#5663)
testcasename0086=BLT Test cases\BLT_BltFast - Verify RLE recompression triggered
testcasename0085=BLT Test cases\BLT_BltFast - MoveToSytemMemoryTest
testcasename0084=BLT Test cases\BLT_BltFast, SRCKEY, From/To same surface (TC#3.6.97b)
testcasename0083=BLT Test cases\BLT_BltFast From/To Same Surface(TC#3.6.97a)
testcasename0082=BLT Test cases\BLT, Stretch (Wx2, Hx.75), AGP to Pri
testcasename0081=BLT Test cases\BLT, Stretch (Wx2, Hx.75), Sys to Pri
testcasename0080=BLT Test cases\BLT, Stretch (Wx2, Hx.75), VMem to Pri
testcasename0079=BLT Test cases\BLT, Shrink, (3/4), AGP To Primary
testcasename0078=BLT Test cases\BLT, Shrink, (3/4), Sys To Primary
testcasename0077=BLT Test cases\BLT, Shrink, (3/4), VMem To Primary
testcasename0076=BLT Test cases\BLT Color Fill AGP Mem(TC 3.6.57)
testcasename0075=BLT Test cases\BLT Color Fill SysMem(TC 3.6.57)
testcasename0074=BLT Test cases\BLT Color Fill Primary(TC 3.6.57)
testcasename0073=BLT Test cases\BLT, Stretch, Complete Overlap, AGP mem.(TC 3.6.?]
testcasename0072=BLT Test cases\BLT, Stretch, Complete Overlap, Sys. mem.(TC 3.6.?]
testcasename0071=BLT Test cases\BLT, Stretch, Complete Overlap, VMem(primary)(TC 3.6.?]
testcasename0070=BLT Test cases\BLT,Stretch(width only), SRCKEY, AGP to pri(TC 3.6.?]
testcasename0069=BLT Test cases\BLT,Stretch(width only), SRCKEY, VMem to pri(TC 3.6.?]
testcasename0068=BLT Test cases\BLT,Stretch(width only), SRCKEY, Sys to pri(TC 3.6.?]
testcasename0067=BLT Test cases\BLT,Stretch, SRCKEY, AGP to primary(TC 3.6.?]
testcasename0066=BLT Test cases\BLT,Stretch, SRCKEY, VMem to primary(TC 3.6.?]
testcasename0065=BLT Test cases\BLT,Stretch, SRCKEY, System to primary(TC 3.6.?]
testcasename0064=BLT Test cases\BLT, single SRCKEY, AGP to Primary(TC 3.6.60)
testcasename0063=BLT Test cases\BLT, single SRCKEY, VMem to Primary(TC 3.6.60)
testcasename0062=BLT Test cases\BLT, single SRCKEY, System to Primary(TC 3.6.60)
testcasename0061=BLT Test cases\BLT Stretch(width only) x 1.5, AGP to Pri(TC 3.6.51-52)
testcasename0060=BLT Test cases\BLT Stretch(width only) x 1.5, System to Pri(TC 3.6.51-52)
testcasename0059=BLT Test cases\BLT Stretch(width only) x 1.5, VMem to Pri(TC 3.6.51-52)
testcasename0058=BLT Test cases\BLT Shrink (1/2), AGP to Primary(TC 3.6.53-54)
testcasename0057=BLT Test cases\BLT Shrink (1/2), System to Primary(TC 3.6.53-54)
testcasename0056=BLT Test cases\BLT Shrink (1/2), VMem to Primary(TC 3.6.53-54)
testcasename0055=BLT Test cases\BLT Stretch x 1.5, AGP to Primary(TC 3.6.51-52)
testcasename0054=BLT Test cases\BLT Stretch x 1.5, System to Primary(TC 3.6.51-52)
testcasename0053=BLT Test cases\BLT Stretch x 1.5, VMem to Primary(TC 3.6.51-52)
testcasename0052=BLT Test cases\BLT Stretch x 2, AGP to Primary(TC 3.6.49-50)
testcasename0051=BLT Test cases\BLT Stretch x 2, System to Primary(TC 3.6.49-50)
testcasename0050=BLT Test cases\BLT Stretch x 2, VMem to Primary(TC 3.6.49-50)
testcasename0049=BLT Test cases\BLT Basic, AGP to Primary(TC 3.6.48, 3.6.103)
testcasename0048=BLT Test cases\BLT Basic, System to Primary(TC 3.6.48, 3.6.107)
testcasename0047=BLT Test cases\BLT Basic, VMem to Primary(TC 3.6.48, 3.6.103)
testcasename0046=BLT Test cases\BLT Basic, Offscreen Surfaces(TC 3.6.101-102, 2.6.105-106)
testcasename0045=CLIP Test cases\CLIP_QueryInterface
testcasename0044=CLIP Test cases\CLIP_QueryInterface Invalid Params Test
testcasename0043=CLIP Test cases\CLIP_SetHWnd/GetHWnd Test(TC 5.5.4, 5.9.5)
testcasename0042=PAL Test cases\PAL_IV_QueryInterface
testcasename0041=PAL Test cases\PAL_MultiPalSwitch
testcasename0040=PAL Test cases\PAL_palGetPalette Test's surface get palette
testcasename0039=PAL Test cases\PAL_Palette Query Interface Invalid Test
testcasename0038=PAL Test cases\PAL_Palette AddRef/Release Test (TC 4.2.2-3, 4.3.2-3 )
testcasename0037=PAL Test cases\PAL_Palette Initialize Test(TC 4.6.3)
testcasename0036=PAL Test cases\PAL_Verify Palette Entries Untouched(Regress Nash #7535)
testcasename0035=PAL Test cases\PAL_GetEntries/SetEntries (8-Bit)(TC 4.5.7, 4.7.7)
testcasename0034=PAL Test cases\PAL_CreatePalette - Init 256 clrs(TC 2.6.9)
testcasename0033=API Test cases\API_ClassFactory
testcasename0032=API Test cases\API_IV_GetMonitorFrequency
testcasename0031=API Test cases\API_IV_QueryInterface
testcasename0030=API Test cases\API_IV_GetScanLine
testcasename0029=API Test cases\API_IV_Initialize
testcasename0028=API Test cases\API_IV_AddRef
testcasename0027=API Test cases\API_IV_RestoreDisplayMode
testcasename0026=API Test cases\API_IV_Release
testcasename0025=API Test cases\API_IV_EnumSurfaces
testcasename0024=API Test cases\API_IV_GetVerticalBlankStatus
testcasename0023=API Test cases\API_IV_Unlock
testcasename0022=API Test cases\API_IV_GetDisplayMode
testcasename0021=API Test cases\API_IV_GetFourCCCodes
testcasename0020=API Test cases\API_IV_GetAvailableVidMem
testcasename0019=API Test cases\API_IV_SurfQueryInterface
testcasename0018=API Test cases\API_IV_GetGDISurface
testcasename0017=API Test cases\API_GetDeviceIdentifier
testcasename0016=API Test cases\API_SetDisplayMode
testcasename0015=API Test cases\API_GetMonitorFrequency
testcasename0014=API Test cases\API_Initialize
testcasename0013=API Test cases\API_RestoreDisplayMode
testcasename0012=API Test cases\API_Lock
testcasename0011=API Test cases\API_GetDisplayMode
testcasename0010=API Test cases\API_GetCaps
testcasename0009=API Test cases\API_EnumDisplayModes
testcasename0008=API Test cases\API_HEL_CreateSurface
testcasename0007=API Test cases\API_Compact
testcasename0006=API Test cases\API_AddRef/Release
testcasename0005=DCT Test cases\DCT_AGPPrimarySurface
testcasename0004=DCT Test cases\DCT_ColorFillWithSourceSurface
testcasename0003=DCT Test cases\GRPH-0393.1 Mobile Minimum Screen Resolution
testcasename0002=DCT Test cases\PC99 14.23 Low-Res Support
testcasename0001=DCT Test cases\PC98_22 (PC97 20) Perform Double Buffer Swaps with no tearing
testcasename0000=DCT Test cases\PC98_21 (PC97 19) Transparent Blter
