[DirectDraw Test Application]
BufferSize.Window=51200
LogFile.Log File=c:\ddtests\fnddraw.log
Cmd.Size=1
Cmd.Hex0000=00
ModesToTest=4
DirectDrawInterface=2
DirectDrawSurfaceInterface=1
DirectDrawInitStyle=2
TreatOtherAsPass=0
MonitorIndex=0
LogBMP=0
StopOnFail=0
Position=0, 0, 1024, 690
Options=387
RunCount=1
Search=failure
LogWindowLevel=10
LogLog FileLevel=10
FontName=Courier
FontAttr=-2 400 0 131585
NumTests=9
testcasename0008=MEMMAN Test cases\MEMMAN - Random Create/Release System Memory surfaces Test
testcasename0007=MEMMAN Test cases\MEMMAN - Consume Half SysMem Test
testcasename0006=MEMMAN Test cases\MEMMAN_GetAvailableVidMem(TC 3.6.?]
testcasename0005=MEMMAN Test cases\MEMMAN - Create/Verify All Video Memory Types(TC ??]
testcasename0004=MEMMAN Test cases\MEMMAN - Video Memory Reuse Test(TC 6.1.2)
testcasename0003=MEMMAN Test cases\MEMMAN - Rand Create/Release AGP surfaces 100X Test(TC 6.1.3)
testcasename0002=MEMMAN Test cases\MEMMAN - Rand Create/Release Video Memory surfaces 100X Test(TC 6.1.3)
testcasename0001=MEMMAN Test cases\MEMMAN - Test VidMem/AGP boundary for MipMap chains
testcasename0000=MEMMAN Test cases\MEMMAN - Consume All Video Mem Test(TC 6.1.1)
